In [1]:
import numpy as np
import cv2 as cv
import glob
import random
import winsound, time, os, sys


In [2]:
# find the data file with extension .npz
outfile = glob.glob("*.npz")
outfile = outfile[0]

# load the npz file with objpoints and imgpoints array
npzfile = np.load(outfile)

# extract the two arrays...
objpoints = npzfile["objpoints"]
imgpoints = npzfile["imgpoints"]

len(objpoints)
len(imgpoints)


627

In [4]:
# use this cell to modify how many images are used as reference...
ref_images = 200    # how many images to use? 

objp, imgp = [], []
indexes = []

# select random images... 
for i in range(ref_images):
    while True:
        index = random.randint(0, len(objpoints)-1)
        if not index in indexes:
            indexes.append(index)
            objp.append(objpoints[index])
            imgp.append(imgpoints[index])
            break
        else:
            continue
            
print(indexes)

[275, 419, 492, 186, 622, 593, 529, 311, 285, 23, 129, 52, 379, 28, 193, 257, 301, 413, 581, 366, 602, 108, 230, 594, 483, 20, 8, 391, 584, 368, 380, 18, 167, 539, 446, 223, 502, 184, 515, 97, 162, 248, 355, 267, 22, 277, 151, 148, 172, 417, 47, 137, 219, 424, 133, 369, 24, 143, 261, 241, 244, 211, 300, 75, 385, 48, 509, 209, 99, 367, 128, 329, 527, 500, 94, 489, 64, 253, 378, 158, 19, 120, 119, 302, 232, 181, 605, 501, 436, 173, 316, 190, 388, 592, 123, 477, 389, 114, 472, 60, 595, 571, 63, 349, 441, 213, 608, 503, 67, 530, 351, 287, 523, 458, 202, 87, 269, 357, 603, 273, 387, 53, 332, 370, 227, 256, 418, 161, 263, 242, 614, 34, 433, 92, 610, 194, 507, 476, 442, 462, 68, 469, 583, 364, 45, 451, 513, 252, 416, 564, 175, 381, 309, 212, 0, 260, 350, 132, 578, 521, 562, 536, 473, 444, 390, 296, 558, 326, 214, 286, 518, 305, 243, 203, 168, 327, 89, 236, 38, 40, 557, 438, 96, 588, 428, 131, 330, 609, 611, 101, 488, 84, 113, 526, 125, 189, 589, 375, 467, 117]


In [5]:
# camera calibration

startTime = time.time()

frame_width  = w = 1920
frame_height = h = 1080

# determine camera matrix, distortion coefficients, 
# rotation and translation vectors
rms, camera_matrix, dist_coefs, rvecs, tvecs = cv.calibrateCamera(
                                                objp, imgp, 
                                                (frame_width,frame_height), None, None)

print("\nRMS", rms, "\n")
print("Camera Matrix: \n", camera_matrix)
print("distortion coefficients: ", dist_coefs.ravel(), "\n")

# compute focal lengths
fx = camera_matrix[0][0]   # focal length in x-direction
fy = camera_matrix[1][1]   # focal length in y-direction
W  = 4                 # sensor width in mm    6.3 x 4.7mm
H  = 3                # sensor height in mm

Fx = fx * W/w
Fy = fy * H/h

print("Focal length in x = {:.2f} mm".format(Fx))
print("Focal length in y = {:.2f} mm".format(Fy))
winsound.Beep(440, 1000)
print("Processed {:.0f} images in {:.1f} s\n".format(ref_images, time.time()-startTime))



RMS 1.1375271702556036 

Camera Matrix: 
 [[1.87275285e+03 0.00000000e+00 9.75764866e+02]
 [0.00000000e+00 1.87696998e+03 5.42590101e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
distortion coefficients:  [ 1.58175072e-01 -6.59545156e-01  1.10951578e-03 -7.72102192e-04
  1.87636309e+00] 

Focal length in x = 3.90 mm
Focal length in y = 5.21 mm
Processed 200 images in 1487.4 s



In [6]:
print( indexes)

[275, 419, 492, 186, 622, 593, 529, 311, 285, 23, 129, 52, 379, 28, 193, 257, 301, 413, 581, 366, 602, 108, 230, 594, 483, 20, 8, 391, 584, 368, 380, 18, 167, 539, 446, 223, 502, 184, 515, 97, 162, 248, 355, 267, 22, 277, 151, 148, 172, 417, 47, 137, 219, 424, 133, 369, 24, 143, 261, 241, 244, 211, 300, 75, 385, 48, 509, 209, 99, 367, 128, 329, 527, 500, 94, 489, 64, 253, 378, 158, 19, 120, 119, 302, 232, 181, 605, 501, 436, 173, 316, 190, 388, 592, 123, 477, 389, 114, 472, 60, 595, 571, 63, 349, 441, 213, 608, 503, 67, 530, 351, 287, 523, 458, 202, 87, 269, 357, 603, 273, 387, 53, 332, 370, 227, 256, 418, 161, 263, 242, 614, 34, 433, 92, 610, 194, 507, 476, 442, 462, 68, 469, 583, 364, 45, 451, 513, 252, 416, 564, 175, 381, 309, 212, 0, 260, 350, 132, 578, 521, 562, 536, 473, 444, 390, 296, 558, 326, 214, 286, 518, 305, 243, 203, 168, 327, 89, 236, 38, 40, 557, 438, 96, 588, 428, 131, 330, 609, 611, 101, 488, 84, 113, 526, 125, 189, 589, 375, 467, 117]


In [7]:
# refine the camera matrix
newcameramtx, roi = cv.getOptimalNewCameraMatrix(camera_matrix, 
                                                dist_coefs, (w,h), 1, (w,h))

print("New Camera Matrix: \n", newcameramtx)
print("ROI = ", roi)

New Camera Matrix: 
 [[1.92431360e+03 0.00000000e+00 9.73515460e+02]
 [0.00000000e+00 1.89481995e+03 5.43054368e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
ROI =  (16, 19, 1890, 1042)


In [ ]:
def cameraMatrix(no_images, npzFileName, w = 1920, h = 1080):
    # timing of the function
    startTime = time.time() 
    
    # Find and read the .npz file with data in
    npzfile = np.load(npzFileName)
    
    # extract the object and image points
    objpoints = npzfile["objpoints"]
    imgpoints = npzfile["imgpoints"]
    objp      = objpoints[:no_images+1]   # only take the first n no. images
    imgp      = imgpoints[:no_images+1]
    
    # determine the RMS projection error, camera matrix, 
    # distortion coefficients, rotation and translation vectors
    rms, camera_matrix, dist_coefficients, rvecs, tvecs = cv.calibrateCamera(
                                                          objp, imgp, 
                                                          (w,h), None, None)
    
    #fovx, fovy, focalLength, principalPoint, aspectRatio = cv.calibrationMatrixValues(
    #                                                       camera_matrix, (w,h), 
    #                                                      sensorWidth, sensorHeight
    
    
    print("Processed {:.0f} images in {:.1f} s".format(no_images, time.time()-startTime))
    print("\nRMS", rms, "\n")
    print("Camera Matrix: \n", camera_matrix)
    print("distortion coefficients: ", dist_coefficients.ravel(), "\n")
    
    # refine the camera matrix
    newcameramtx, roi = cv.getOptimalNewCameraMatrix(camera_matrix, 
                                                dist_coefficients, (w,h), 1, (w,h))
    
    print("Optimised Camera Matrix: \n", newcameramtx, "\n \n")
    print("################################################################ \n")
    
    return no_images, rms, camera_matrix, dist_coefficients, newcameramtx
    



In [ ]:
imgs, RMS, cameramtx, dist_coefficients, optimalCameraMtx = [], [], [], [], []

for no_images in np.arange(10, 60, 10):
    images, rms, camera_matrix, dist_coefs, newcameramtx = cameraMatrix(no_images, outfile)
    imgs.append(images)
    RMS.append(rms)
    cameramtx.append(camera_matrix)
    dist_coefficients.append(dist_coefs)
    optimalCameraMtx.append(newcameramtx)

In [ ]:
a = np.arange(10,60,10)
b = a.tolist()